config/routes.rb
Chess::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :games do
    member do
      put :join
    end
  end
  resources :pieces, only: [:update]

  root 'games#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :pieces
  belongs_to :white_player, class_name: 'User'
  belongs_to :black_player, class_name: 'User'

  validates :name, presence: true

  after_create :populate_board!
  after_create :set_default_turn!

  def set_default_turn!
    update_attributes(turn: white_player_id)
  end

  def opponent
    turn == white_player_id ? black_player_id : white_player_id
  end

  def change_turns!
    update_attributes(turn: opponent)
  end

  private

  def populate_board!
    if pieces.empty?
      # White Pieces
      (0..7).each do |i|
        Pawn.create(
          game_id: id,
          x_position: i,
          y_position: 1,
          player_id: white_player_id
          )
      end

      Rook.create(game_id: id, x_position: 0, y_position: 0, player_id: white_player_id)
      Rook.create(game_id: id, x_position: 7, y_position: 0, player_id: white_player_id)

      Knight.create(game_id: id, x_position: 1, y_position: 0, player_id: white_player_id)
      Knight.create(game_id: id, x_position: 6, y_position: 0, player_id: white_player_id)

      Bishop.create(game_id: id, x_position: 2, y_position: 0, player_id: white_player_id)
      Bishop.create(game_id: id, x_position: 5, y_position: 0, player_id: white_player_id)

      Queen.create(game_id: id, x_position: 3, y_position: 0, player_id: white_player_id)
      King.create(game_id: id, x_position: 4, y_position: 0, player_id: white_player_id)

      # Black Pieces
      (0..7).each do |i|
        Pawn.create(
          game_id: id,
          x_position: i,
          y_position: 6,
          player_id: black_player_id
        )
      end

      Rook.create(game_id: id, x_position: 0, y_position: 7, player_id: black_player_id)
      Rook.create(game_id: id, x_position: 7, y_position: 7, player_id: black_player_id)

      Knight.create(game_id: id, x_position: 1, y_position: 7, player_id: black_player_id)
      Knight.create(game_id: id, x_position: 6, y_position: 7, player_id: black_player_id)

      Bishop.create(game_id: id, x_position: 2, y_position: 7, player_id: black_player_id)
      Bishop.create(game_id: id, x_position: 5, y_position: 7, player_id: black_player_id)

      Queen.create(game_id: id, x_position: 3, y_position: 7, player_id: black_player_id)
      King.create(game_id: id, x_position: 4, y_position: 7, player_id: black_player_id)
    else
      flash[:notice] = 'An error has occured.'
      redirect_to root_path
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :join]

  def index
    if current_user
      @open_games = Game.where('black_player_id' => nil).where('white_player_id != ?', current_user.id)
    else
      @open_games = Game.where('black_player_id' => nil)
    end
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.create(game_params)

    if @game.valid?
      redirect_to game_path(@game)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @game = Game.find(params[:id])
  end

  def join
    @game = Game.find(params[:id])
    if current_user.id == @game.white_player_id
      return render text: 'Not Allowed', status: :forbidden
    else
      @game.update_attributes(black_player_id: current_user.id)
      redirect_to game_path(@game)
    end
  end

  private

  def game_params
    params.require(:game).permit(:name, :white_player_id)
  end
end

app/helpers/game_helper.rb
module GameHelper
end

app/views/games/index.html.erb
<div class="hero">
  <div class="title-text col-xs-10 col-xs-offset-1">
    <h1>WELCOME!</h1>
    <br />
    <h3>Join an open game below or start a new game</h3>
    <br />
  </div>
</div>
<br />
<br />
<div class="booyah-box">
  <br />
  <h2>Open Games:</h2>
  <br />
  <ul>
    <% @open_games.each do |game| %>
      <li><%= game.name %> with <%= User.find(game.white_player_id).username %> <%= link_to "Join Game", join_game_path(game), method: :put, :class => "btn btn-primary" %></li>
      <br />
    <% end %>
  </ul>
  <br />
</div>
<br />
<br />

app/views/games/new.html.erb
<div class="new-game col-xs-12 col-sm-4 col-sm-offset-1">  
  <h1>Start a New Game</h1>
  <br/>
  <%= simple_form_for @game do |f| %>
    <%= f.input :name %>
    <%= f.input :white_player_id, :as => :hidden, :input_html => { :value => current_user.id } %>
    <br/>
    <%= f.button :submit, "Create Game", :class => 'btn btn-primary' %>
    <% end %>
  <br/>
</div>

app/views/games/show.html.erb
<h1 class="text-center">Game: <%= @game.name %></h1>
<table class="board">
<% rank = 7 %>
	<% 8.times do %>
		<% file = 0 %>
		<tr>
			<% 8.times do %>
				<% piece = @game.pieces.find{|piece| piece.x_position == file && piece.y_position == rank} %>
				<td class="droppable" id="<%= "#{file}#{rank}" %>">
					<% if piece %>
						<%= image_tag "#{piece.color.downcase}-#{piece.type.downcase}.svg", class: "draggable", :alt => "#{piece.color} #{piece.type}", data: {update_url: "#{piece_path(piece)}"} %>
					<% end %>
				</td>
				<% file +=1 %>
			<% end %>
		</tr>
		<% rank -= 1 %>
	<% end %>
</table>