config/routes.rb
Chess::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :games do
    member do
      put :join
    end
  end
  resources :pieces, only: [:update]

  root 'games#index'

end

app/views/layouts/_facebook.html.erb
<%= link_to image_tag("facebook.png", width: "125", height: "30", alt: "Log in with Facebook"), user_omniauth_authorize_path(:facebook) %>

app/views/layouts/_login_modal.html.erb
<div class="modal fade" id="logInModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button class="close" data-dismiss="modal">x</button>
        <h2>Log in</h2>
      </div>
        <div class="modal-body">
          <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
            <%= devise_error_messages! %>
          
            <div class="field">
              <%= f.email_field :email, placeholder: 'Email', autofocus: true %>
            </div>
          
            <div class="field">
              <% if @minimum_password_length %>
              <em>(<%= @minimum_password_length %> characters minimum)</em>
              <% end %><br />
              <%= f.password_field :password, placeholder: 'Password', autocomplete: "off" %>
            </div>

            <% if devise_mapping.rememberable? -%>
              <div class="field">
                <%= f.check_box :remember_me %>
                <%= f.label :remember_me %>
              </div>
            <% end -%>  

            <div class="actions">
              <%= f.submit "Log in" %>
            </div>
          <% end %>
        </div>
      <div class="modal-footer">
        <%= render "devise/shared/links" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_signup_modal.html.erb
<div class="modal fade" id="signUpModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">  
      <div class="modal-header">
        <button class="close" data-dismiss="modal">x</button>
        <h2>Sign up</h2>
      </div>
        <div class="modal-body">
          <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
            <div class="field">
              <%= f.email_field :email, placeholder: 'Email', autofocus: true %>
            </div>

            <div class="field">
              <%= f.text_field :username, placeholder: 'Username' %>
            </div>  

            <div class="field">
              <%= f.password_field :password, placeholder: 'Password', autocomplete: "off" %>
            </div>

            <div class="field">
              <%= f.password_field :password_confirmation, placeholder: 'Password Confirmation', autocomplete: "off" %>
            </div>
          
            <div class="actions">
              <%= f.submit "Sign up" %>
            </div>
          <% end %>
        </div>
      <div class="modal-footer">
        <%= render "devise/shared/links" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chess</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'CHESS by Deep Ruby', root_url, :class => "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to 'New Game', new_game_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to current_user.username, '#' %></li>
            <li><%= link_to 'Log Out', destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <li><%= link_to 'Log In', new_user_session_path %></li>
            <li><%= render "layouts/facebook" %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
	
  <%= yield %>

  <div class="footer">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <br />
      Created by Team <span class="deep-ruby">Deep Ruby</span>: Ford Fischer, James Foster, Ken Mak, Nin Yeung
    <div>
  </div>
</body>
</html>